// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleSearch.Data;

namespace PeopleSearch.Data.Migrations
{
    [DbContext(typeof(PeopleSearchContext))]
    partial class PeopleSearchContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PeopleSearch.Data.Domain.Person", b =>
                {
                    b.Property<long>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Avatar");

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("PeopleSearch.Data.Domain.PersonalInterest", b =>
                {
                    b.Property<long>("PersonalInterestId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Interest");

                    b.Property<long?>("PersonId");

                    b.HasKey("PersonalInterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonalInterest");
                });

            modelBuilder.Entity("PeopleSearch.Data.Domain.Person", b =>
                {
                    b.OwnsOne("PeopleSearch.Data.Domain.Address", "Address", b1 =>
                        {
                            b1.Property<long>("PersonId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("City");

                            b1.Property<string>("State");

                            b1.Property<string>("Street");

                            b1.Property<string>("Zip");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.HasOne("PeopleSearch.Data.Domain.Person")
                                .WithOne("Address")
                                .HasForeignKey("PeopleSearch.Data.Domain.Address", "PersonId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("PeopleSearch.Data.Domain.PersonalInterest", b =>
                {
                    b.HasOne("PeopleSearch.Data.Domain.Person")
                        .WithMany("PersonalInterests")
                        .HasForeignKey("PersonId");
                });
#pragma warning restore 612, 618
        }
    }
}
